require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'project_requirements/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
